USE [YAPALQCM]
GO
/****** Object:  Table [dbo].[INSCRIPTIONS]    Script Date: 10/08/2017 16:55:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSCRIPTIONS](
	[idUser] [int] NOT NULL,
	[idSession] [int] NOT NULL,
 CONSTRAINT [PK_INSCRIPTIONS] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC,
	[idSession] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUESTIONS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTIONS](
	[idQuestion] [int] IDENTITY(1,1) NOT NULL,
	[enonce] [nvarchar](100) NOT NULL,
	[image] [nvarchar](50) NULL,
 CONSTRAINT [PK_QUESTIONS] PRIMARY KEY CLUSTERED 
(
	[idQuestion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUESTIONS_THEMES]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTIONS_THEMES](
	[idTheme] [int] NOT NULL,
	[idQuestion] [int] NOT NULL,
 CONSTRAINT [PK_QUESTIONSTHEMES] PRIMARY KEY CLUSTERED 
(
	[idTheme] ASC,
	[idQuestion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUESTIONS_THEMES_ENCOURS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTIONS_THEMES_ENCOURS](
	[idSection] [int] NOT NULL,
	[idTestSession] [int] NOT NULL,
	[idUser] [int] NOT NULL,
	[idTheme] [int] NOT NULL,
	[idQuestion] [int] NOT NULL,
	[isCheck] [bit] NULL,
	[isAnswered] [bit] NULL,
 CONSTRAINT [PK_QUESTIONS_THEMES_ENCOURS] PRIMARY KEY CLUSTERED 
(
	[idTheme] ASC,
	[idQuestion] ASC,
	[idSection] ASC,
	[idTestSession] ASC,
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[REPONSES]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPONSES](
	[idReponse] [int] IDENTITY(1,1) NOT NULL,
	[enonce] [nvarchar](150) NOT NULL,
	[isCorrect] [bit] NOT NULL,
	[idQuestion] [int] NOT NULL,
 CONSTRAINT [PK_REPONSES] PRIMARY KEY CLUSTERED 
(
	[idReponse] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[REPONSES_ENCOURS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPONSES_ENCOURS](
	[idUser] [int] NOT NULL,
	[idTest] [int] NOT NULL,
	[idQuestion] [int] NOT NULL,
	[idReponse] [int] NOT NULL,
	[isCheck] [bit] NULL,
	[isMarquee] [bit] NULL,
 CONSTRAINT [PK_REPONSES_ENCOURS] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC,
	[idTest] ASC,
	[idQuestion] ASC,
	[idReponse] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RESULTATS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESULTATS](
	[idUser] [int] NOT NULL,
	[idTest] [int] NOT NULL,
	[idSession] [int] NOT NULL,
	[tempsEcoule] [bigint] NOT NULL,
	[seuilObtenu] [float] NOT NULL,
 CONSTRAINT [PK_RESULTATS] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC,
	[idSession] ASC,
	[idTest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_RESULTATS] UNIQUE NONCLUSTERED 
(
	[idUser] ASC,
	[idTest] ASC,
	[idSession] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RESULTATS_SECTION]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESULTATS_SECTION](
	[idTest] [int] NOT NULL,
	[idTheme] [int] NOT NULL,
	[idSession] [int] NOT NULL,
	[idUser] [int] NOT NULL,
	[score] [int] NOT NULL,
 CONSTRAINT [PK_RESULTATS_SECTION] PRIMARY KEY CLUSTERED 
(
	[idTest] ASC,
	[idTheme] ASC,
	[idSession] ASC,
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[idRole] [int] IDENTITY(1,1) NOT NULL,
	[role] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED 
(
	[idRole] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[SECTIONS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECTIONS](
	[idTest] [int] NOT NULL,
	[idTheme] [int] NOT NULL,
	[nombreQuestions] [int] NOT NULL,
 CONSTRAINT [PK_SECTIONS] PRIMARY KEY CLUSTERED 
(
	[idTest] ASC,
	[idTheme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[SECTIONS_ENCOURS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECTIONS_ENCOURS](
	[idSection] [int] NOT NULL,
	[idTestSession] [int] NOT NULL,
	[idUser] [int] NOT NULL,
	[isValid] [bit] NULL,
 CONSTRAINT [PK_SECTIONS_ENCOURS] PRIMARY KEY CLUSTERED 
(
	[idSection] ASC,
	[idTestSession] ASC,
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[SESSIONS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SESSIONS](
	[idSession] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime] NULL,
	[nombrePlaces] [int] NOT NULL,
 CONSTRAINT [PK_SESSIONS] PRIMARY KEY CLUSTERED 
(
	[idSession] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TEST_SESSIONS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TEST_SESSIONS](
	[idSession] [int] NOT NULL,
	[idTest] [int] NOT NULL,
	[heure] [time](7) NULL,
	[isBegin] [bit] NOT NULL,
	[tempsEcoule] [bigint] NOT NULL,
 CONSTRAINT [PK_TEST_SESSIONS] PRIMARY KEY CLUSTERED 
(
	[idSession] ASC,
	[idTest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TESTS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TESTS](
	[idTest] [int] IDENTITY(1,1) NOT NULL,
	[nomTest] [nvarchar](100) NOT NULL,
	[seuilAcquis] [float] NOT NULL,
	[seuilEnCoursAcquisition] [float] NOT NULL,
	[duree] [bigint] NOT NULL,
 CONSTRAINT [PK_TEST] PRIMARY KEY CLUSTERED 
(
	[idTest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TESTS_EN_COURS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TESTS_EN_COURS](
	[idUser] [int] NOT NULL,
	[idTest] [int] NOT NULL,
	[chrono] [bigint] NULL,
 CONSTRAINT [PK_TESTS_EN_COURS] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC,
	[idTest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THEMES]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THEMES](
	[idTheme] [int] IDENTITY(1,1) NOT NULL,
	[nom] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_THEMES] PRIMARY KEY CLUSTERED 
(
	[idTheme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UTILISATEURS]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTILISATEURS](
	[idUser] [int] IDENTITY(1,1) NOT NULL,
	[idRole] [int] NOT NULL,
	[password] [nvarchar](100) NOT NULL,
	[nom] [nvarchar](100) NOT NULL,
	[prenom] [nvarchar](100) NOT NULL,
	[dateNaissance] [datetime] NULL,
	[adresseEmail] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_UTLISATEURS] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UTILISATEURS_ROLES]    Script Date: 10/08/2017 16:55:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTILISATEURS_ROLES](
	[idUser] [int] NOT NULL,
	[idRole] [int] NOT NULL,
	[adresseEmail] [nvarchar](200) NOT NULL,
	[role] [nvarchar](100) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[INSCRIPTIONS]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPTIONS_SESSIONS] FOREIGN KEY([idSession])
REFERENCES [dbo].[SESSIONS] ([idSession])
GO
ALTER TABLE [dbo].[INSCRIPTIONS] CHECK CONSTRAINT [FK_INSCRIPTIONS_SESSIONS]
GO
ALTER TABLE [dbo].[INSCRIPTIONS]  WITH CHECK ADD  CONSTRAINT [FK_INSCRIPTIONS_UTILISATEURS] FOREIGN KEY([idUser])
REFERENCES [dbo].[UTILISATEURS] ([idUser])
GO
ALTER TABLE [dbo].[INSCRIPTIONS] CHECK CONSTRAINT [FK_INSCRIPTIONS_UTILISATEURS]
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES]  WITH CHECK ADD  CONSTRAINT [FK_QUESTIONSTHEMES_QUESTIONS] FOREIGN KEY([idQuestion])
REFERENCES [dbo].[QUESTIONS] ([idQuestion])
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES] CHECK CONSTRAINT [FK_QUESTIONSTHEMES_QUESTIONS]
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES]  WITH CHECK ADD  CONSTRAINT [FK_QUESTIONSTHEMES_THEMES] FOREIGN KEY([idTheme])
REFERENCES [dbo].[THEMES] ([idTheme])
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES] CHECK CONSTRAINT [FK_QUESTIONSTHEMES_THEMES]
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES_ENCOURS]  WITH CHECK ADD  CONSTRAINT [FK_QUESTIONSTHEMESENCOURS_SECTIONSENCOURS] FOREIGN KEY([idSection], [idTestSession], [idUser])
REFERENCES [dbo].[SECTIONS_ENCOURS] ([idSection], [idTestSession], [idUser])
GO
ALTER TABLE [dbo].[QUESTIONS_THEMES_ENCOURS] CHECK CONSTRAINT [FK_QUESTIONSTHEMESENCOURS_SECTIONSENCOURS]
GO
ALTER TABLE [dbo].[REPONSES]  WITH CHECK ADD  CONSTRAINT [FK_REPONSES_QUESTIONS] FOREIGN KEY([idQuestion])
REFERENCES [dbo].[QUESTIONS] ([idQuestion])
GO
ALTER TABLE [dbo].[REPONSES] CHECK CONSTRAINT [FK_REPONSES_QUESTIONS]
GO
ALTER TABLE [dbo].[REPONSES_ENCOURS]  WITH CHECK ADD  CONSTRAINT [FK_REPONSES_ENCOURS_REPONSES_ENCOURS] FOREIGN KEY([idUser], [idTest])
REFERENCES [dbo].[TESTS_EN_COURS] ([idUser], [idTest])
GO
ALTER TABLE [dbo].[REPONSES_ENCOURS] CHECK CONSTRAINT [FK_REPONSES_ENCOURS_REPONSES_ENCOURS]
GO
ALTER TABLE [dbo].[RESULTATS]  WITH CHECK ADD  CONSTRAINT [FK_RESULTATS_TESTSESSIONS] FOREIGN KEY([idSession], [idTest])
REFERENCES [dbo].[TEST_SESSIONS] ([idSession], [idTest])
GO
ALTER TABLE [dbo].[RESULTATS] CHECK CONSTRAINT [FK_RESULTATS_TESTSESSIONS]
GO
ALTER TABLE [dbo].[RESULTATS]  WITH CHECK ADD  CONSTRAINT [FK_RESULTATS_UTILISATEURS] FOREIGN KEY([idUser])
REFERENCES [dbo].[UTILISATEURS] ([idUser])
GO
ALTER TABLE [dbo].[RESULTATS] CHECK CONSTRAINT [FK_RESULTATS_UTILISATEURS]
GO
ALTER TABLE [dbo].[RESULTATS_SECTION]  WITH CHECK ADD  CONSTRAINT [FK_RESULTATS_SECTION_RESULTATS] FOREIGN KEY([idUser], [idTest], [idSession])
REFERENCES [dbo].[RESULTATS] ([idUser], [idTest], [idSession])
GO
ALTER TABLE [dbo].[RESULTATS_SECTION] CHECK CONSTRAINT [FK_RESULTATS_SECTION_RESULTATS]
GO
ALTER TABLE [dbo].[RESULTATS_SECTION]  WITH CHECK ADD  CONSTRAINT [FK_RESULTATS_SECTION_SECTIONS] FOREIGN KEY([idTest], [idTheme])
REFERENCES [dbo].[SECTIONS] ([idTest], [idTheme])
GO
ALTER TABLE [dbo].[RESULTATS_SECTION] CHECK CONSTRAINT [FK_RESULTATS_SECTION_SECTIONS]
GO
ALTER TABLE [dbo].[SECTIONS]  WITH CHECK ADD  CONSTRAINT [FK_SECTIONS_TESTS] FOREIGN KEY([idTest])
REFERENCES [dbo].[TESTS] ([idTest])
GO
ALTER TABLE [dbo].[SECTIONS] CHECK CONSTRAINT [FK_SECTIONS_TESTS]
GO
ALTER TABLE [dbo].[SECTIONS]  WITH CHECK ADD  CONSTRAINT [FK_SECTIONS_THEMES] FOREIGN KEY([idTheme])
REFERENCES [dbo].[THEMES] ([idTheme])
GO
ALTER TABLE [dbo].[SECTIONS] CHECK CONSTRAINT [FK_SECTIONS_THEMES]
GO
ALTER TABLE [dbo].[TEST_SESSIONS]  WITH CHECK ADD  CONSTRAINT [FK_TESTSESSIONS_SESSIONS] FOREIGN KEY([idSession])
REFERENCES [dbo].[SESSIONS] ([idSession])
GO
ALTER TABLE [dbo].[TEST_SESSIONS] CHECK CONSTRAINT [FK_TESTSESSIONS_SESSIONS]
GO
ALTER TABLE [dbo].[TEST_SESSIONS]  WITH CHECK ADD  CONSTRAINT [FK_TESTSESSIONS_TEST] FOREIGN KEY([idTest])
REFERENCES [dbo].[TESTS] ([idTest])
GO
ALTER TABLE [dbo].[TEST_SESSIONS] CHECK CONSTRAINT [FK_TESTSESSIONS_TEST]
GO
ALTER TABLE [dbo].[UTILISATEURS]  WITH CHECK ADD  CONSTRAINT [FK_UTLISATEURS_ROLES] FOREIGN KEY([idRole])
REFERENCES [dbo].[ROLES] ([idRole])
GO
ALTER TABLE [dbo].[UTILISATEURS] CHECK CONSTRAINT [FK_UTLISATEURS_ROLES]
GO
